version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adonis_server
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: your_db_user
      DB_PASSWORD: your_db_password
      DB_NAME: your_db_name
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    command: >
      sh -c "
      node ace migration:run &&
      node build/server.js
      "
    expose:
      - "3333"

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: your_db_user
      POSTGRES_PASSWORD: your_db_password
      POSTGRES_DB: your_db_name
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cdn:
    image: nginx:alpine
    container_name: nginx_cdn
    volumes:
      - ./build/public/assets:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - "80"
    ports:
      - "8080:80"

volumes:
  postgres_data:
