version: '3.9'

services:
  server:
    build: .
    ports:
      - "3333:3333"
    env_file:
      - .env
    depends_on:
      - postgresql
    command: sh -c "node ace migration:run && node ace db:seed && node bin/server.js"

  postgresql:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf.template:ro
    depends_on:
      - server
    command: /bin/sh -c "envsubst '$$PORT' < /etc/nginx/conf.d/default.conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    environment:
      - PORT=3333

volumes:
  pgdata:
