version: '3.7'

services:
  nextjs:
    build: .
    ports:
      - '3000:3000'
    networks:
      - webnet
    environment:
      - NODE_ENV=production

  nginx:
    image: nginx:latest
    ports:
      - '8080:80'
    depends_on:
      - nextjs
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - webnet

networks:
  webnet:
